### PR TITLE
Sagenet elihei

### PR DESCRIPTION
**Pull request by EliHei2**
-fixed datasets
-fixed requirements with warnings

### CODE REVIEW

**Comment by Koncopd** [comment]
@EliHei2 thank you for the PR. Please remove `.DS_Store` files.

**Comment by Koncopd** [comment]
Thx. Another thing. I think try catch with import is better to move to the import of the whole `sagenet` model, not only `pytorch-geometric`, because without `pytorch-geometric` `sagenet ` is useless anyways, no need to load anything.

**Comment by EliHei2** [comment]
Done!

**Comment by Koncopd** [comment]
@EliHei2 thank you. One last thing, could you please change the imports like 
`from .sagenet.utils import *`
`from .MGA_data import *`
with explicitly stated imports, i.e. writing what exactly you want to import.

Then i will merge.

**Comment by Koncopd** [comment]
Ok, everything looks ok, merging.

**Pull request merged**
