### PR TITLE
add mvTCR

### PR DESCRIPTION
**Pull request by DeepOzean**

### CODE REVIEW

**Comment by M0hammadL** [comment]
could you please update the notebook so that only searches would be imported and remove the pip installation at the beginning, and all commands would be `sca.model.mvtcr.train`

**Comment by Koncopd** [comment]
The example of optional import is here
https://github.com/theislab/scarches/blob/7980a187294204b5fb5d61364bb76c0b809eb945/scarches/models/__init__.py#L6

**Comment by DeepOzean** [comment]
> The example of optional import is here
> 
> https://github.com/theislab/scarches/blob/7980a187294204b5fb5d61364bb76c0b809eb945/scarches/models/__init__.py#L6

Do we need the optional import? I've added mvtcr to the setup of scarches. So it will be automatically installed when someone installs scarches. Also, installing mvtcr doesn't change any other required package.

**Comment by Koncopd** [comment]
@M0hammadL what do you think? Why do you want optional import? I don't see any heavy dependencies in mvtcr.

**Comment by M0hammadL** [comment]
> @M0hammadL what do you think? Why do you want optional import? I don't see any heavy dependencies in mvtcr.

Yeah makes sense, let's install then and not optional

**Comment by Koncopd** [comment]
Actually some miht be still tricky, so i would also prefer optional install.

**Comment by DeepOzean** [comment]
I've checked and all requirements are fulfilled if scarches is installed. So nothing new is added by installing mvtcr. However if someone upgrades scarches, some packages may get updated due to mvtcr. I make it an optional install then. But I will add `pip install mvtcr` back to the notebook.

**Comment by DeepOzean** [comment]
Added more text now, query labels and made mvtcr an optional dependency

**Comment by Koncopd** [comment]
Thank you.
Though i think maybe importing not in models, hm, because `sca.models.mvTCR.models...` looks strange, no?

**Comment by Koncopd** [comment]
ok, discussed, this is fine, merging

**Pull request merged**
